name: 'Automerge'
on: push

jobs:
  merge_to_releases: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: pashoo2/action-automerge_release@master
        with:
          token: ${{ secrets.TOKEN }}
          mainBranchName: 'master'
          releaseBranchPrfix: 'rel'
          releaseBranchTaskPrefix: 'v.'