name: 'Automerge'
on: push

jobs:
merge: # make sure the action works on a clean machine without building
runs-on: ubuntu-latest
steps:
# run the action
 - uses: pashoo2/action-automerge_release@master
 name: run_automerge
 id: run_automerge
 with:
  token: ${{ secrets.TOKEN }}
  mainBranchName: 'master'
  releaseBranchPrfix: 'rel'
  releaseBranchTaskPrefix: 'v.'
  automergePrLabel: 'automerge-conflict'