name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
    # only if PR closed
    types: [closed]

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
        # run the action
      - uses: optimaxdev/action-automerge_release@main
        name: run_automerge
        id: run_automerge
        # PR must be successfully merged and repo succesfully initiated on the previous step
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        with:
          token: ${{ github.token }}
          mainBranchName: 'master'
          releaseBranchTaskPrefix: 'v.'
          releaseBranchPrfix: 'rel'
